export class HomePage {
    constructor(
      public $key: string,
      public title: string,
      public subtitle: string,
      public forTime: string,
      public subheaderLoc: string,
      public subheaderDate: string,
      public cardsTitle: string,
      public cardsSubtitle: string,
      public videoTitle: string,
      public videoSubtitle: string,
      public postsTitle: string,
      public postsSubtitle: string,
      public postsButtonText: string,
      public postsButtonURL: string,
      public onDemandTitle: string,
      public onDemandText: string,
      public onDemandButtonText: string,
      public onDemandButtonURL: string,
      public byTheNumbersTitle: string,
      public byTheNumbersOneNumber: string,
      public byTheNumbersOneSubtitle: string,
      public byTheNumbersTwoNumber: string,
      public byTheNumbersTwoSubtitle: string,
      public byTheNumbersThreeNumber: string,
      public byTheNumbersThreeSubtitle: string,
      public sponsorTitle: string,
      public sponsorOneImg: string,
      public sponsorOneURL: string,
      public sponsorTwoImg: string,
      public sponsorTwoURL: string,
      public sponsorThreeImg: string,
      public sponsorThreeURL: string,
      public sponsorFourImg: string,
      public sponsorFourURL: string,
      public hasCalendar: boolean,
      public calendarTitle: string,
      public calendarSectionTitle: string,
      public uid: string,
    ) {
    }
}
