/*------------------------------------------------
     NG Universal toolkit
------------------------------------------------*/
// generated by @ng-toolkit/serverless
'use strict';
const server = require('./dist/server');
const functions = require('firebase-functions');

const http = functions.https.onRequest((request, response) => {
    if (!request.path) {
        request.url = "/" + request.url;
    } else {
        console.error('error')
    }
    return server.app(request, response);
})
  .catch((error) => {
      console.log(error);
  });

module.exports = {
    http
};